### PR TITLE
Bug 58845 : http request view doesn't display all the parameters

### PR DESCRIPTION
**Pull request by benbenw**

### CODE REVIEW

**Comment by milamberspace** [comment]
Can you provide a test case to show the issue?

**Comment by benbenw** [comment]
you mean a test for the new behavior ?

**Comment by milamberspace** [comment]
Yes, to show which kind of params are missing in the display

**Comment by benbenw** [comment]
I can not add a test for the previous behavior as the method signature is wrong : the query is parsed into a Map<String, String> where you can only have 1 value per parameter name...
If you can have a look at bug 58851, I will add a test with my PR that test that all the parameters are displayed

**Comment by milamberspace** [comment]
Not a junit test, a jmeter test (.jmx)

**Comment by benbenw** [comment]
ok
attached the test I've used for my PR to bugzilla 
run the test and have a look at the result in the request http view
parameters defined in the http sampler are missing
the sampler is fine it's just the display

**Pull request closed without merging**
