### PR TITLE
Add icon for JetBrains Toolbox

### PR DESCRIPTION
**Pull request by vlsi**
I'm not sure there's a square JMeter icon, so I use `JM`.

Toolbox:
Toolbox

IDEA:

IDEA

IDEA Darcula:

IDEA Darcula

Any comments?

### CODE REVIEW

**Review by ham1 — APPROVED** [review]

**Comment by ham1** [comment]
Maybe worth compressing the png using https://tinypng.com/ for example?

**Comment by vlsi** [comment]
Which png do you mean?

**Comment by ham1** [comment]
`.idea/icon.png`?

**Comment by vlsi** [comment]
The dark `M` does not look great in dark themes (see the PR description).

**Comment by vlsi** [comment]
Dark icon can be configured as `.icon/icon_dark.png`

**Pull request merged**
