### PR TITLE
Checkstyle

### PR DESCRIPTION
**Pull request by ham1**
## Description
* Updated to latest checkstyle (v8.5)
* Added many more rules to checkstyle
* Included checking of test files and more file types

## Motivation and Context
Automatically enforcing some of the coding standards/conventions helps improve readability and prevents commits like "Tab police" or commits which only change formatting thus cluttering the history (or leaving it in an inconsistent state to micro-annoy subsequent readers).

## How Has This Been Tested?
`ant clean checkstyle -Djava.awt.headless=true -Dskip.bug52310=true -Dskip.test_https=true test`

## Types of changes

- Dev enhancement

## Checklist:

- [x] My code follows the [code style][style-guide] of this project.
- [x] I have updated the documentation accordingly.

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

### CODE REVIEW

**Comment by romani** [comment]
@ham1 , ReturnCount check is commented out.  Please point me to place where you configure it.

**Comment by romani** [comment]
Looks like a reason was in `maxForVoid` with default value., Right ?

**Comment by ham1** [comment]
Yes, that's correct, I some how missed it in the docs.

I've suggested on https://github.com/checkstyle/checkstyle/issues/5305 that the error message is changed to something like:
`"Return count is 2 (maxForVoid allowed is 1). [ReturnCount10]"`
or
`"Void return count is 2 (max allowed is 1). [ReturnCount10]"`
to perhaps help prevent the confusion.

**Comment by romani** [comment]
@ham1 , if you enforce(ERROR level) more than half of Checks on this project, we can use jmeter project in each commit (in checkstyle) regression testing.

**Comment by ham1** [comment]
@romani, sorry I'm not clear on what, if anything, you'd want me to do/change?

**Comment by romani** [comment]
if master branch of this project (jmeter) start to use about 80 Checks in its config with ERROR severity and no violations reported, we can start to use jmeter in out CI for regression testing. 

just keep enforcing more and more rules, and pin me then you are done.

**Comment by pmouawad** [comment]
Hi team, anybody wants to merge this one ? if not I’ll do it this week-end. Thanks

**Pull request closed without merging**
