### PR TITLE
Added changes to track hits in cumulatedMetrics

### PR DESCRIPTION
**Pull request by victorian**
We needed a way of getting the hits/sec metric for the duration of the test reported in Graphite and hence have modified the GraphiteBackendListener and SamplerMetric to store this information using the SampleResult. We have tested this locally and here is the comparsion between the hits/sec plugin and the chart generated using the Graphite data.
image
image

### CODE REVIEW

**Comment by pmouawad** [comment]
Thanks for your contribution.
It has been integrated with some slight changes within :
https://bz.apache.org/bugzilla/show_bug.cgi?id=58122
http://svn.apache.org/viewvc?view=revision&revision=1690363

Please test nightly build once it is available (tomorrow) and give us feedback.
Regards
Philippe M.
@philmdot

**Comment by victorian** [comment]
Tested and looks good. The only question I have is that we are recording hits for samplers as well (which is always zero), which does not quite make sense to me. If this metric is present for samplers, then it might mislead users in believing that it should contain valid data and might lead to reported bugs. Would you mind elaborating why you chose this implementation?

**Comment by pmouawad** [comment]
Hi,
Sorry for late reply.
Could you provide a PR based on current code so that I see what you mean ?
Thanks

**Comment by pmouawad** [comment]
After further analysis, I understand you might be talking about the piece of code in GraphiteBackendListenerClient#addMetrics
             graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_OK_COUNT, Integer.toString(metric.getSuccesses()));
        graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_KO_COUNT, Integer.toString(metric.getFailures()));
        graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_ALL_COUNT, Integer.toString(metric.getTotal()));
        graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_ALL_HITS_COUNT, Integer.toString(metric.getHits()));

        // See https://bz.apache.org/bugzilla/show_bug.cgi?id=57350
        if(metric.getTotal() > 0) { 


Which should be maybe:

             if(metric.getTotal() > 0) { 
            graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_OK_COUNT, Integer.toString(metric.getSuccesses()));
            graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_KO_COUNT, Integer.toString(metric.getFailures()));
            graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_ALL_COUNT, Integer.toString(metric.getTotal()));
            graphiteMetricsManager.addMetric(timestampInSeconds, contextName, METRIC_ALL_HITS_COUNT, Integer.toString(metric.getHits()));

Do I understand well ?
Thanks

**Pull request closed without merging**
