### PR TITLE
Add expand/collapse all menu in render XML view

### PR DESCRIPTION
**Pull request by max3163**
In the view result tree listener, when you display the result of a sampler in XML, actually you can't collapse / expand all nodes of the JTree. Find a node can become boring in this way... 
This PR allow to do this with a popopmenu and collapse / expand all nodes from the selected one.

image

To expand all , just select the root node.

### CODE REVIEW

**Comment by max3163** [comment]
Do you think it's a good idea ?

**Comment by FSchumacher** [comment]
Looks useful to me.

Something I always try, when something is expandable/collapsable is to use the left/right cursor to expand/collapse. Maybe this would be useful and simple to implement, what do you think?

**Comment by pmouawad** [comment]
Looks useful to me also although I think an XML formatter which allows collapsing of nodes in editor would be much better.

**Comment by pmouawad** [comment]
Hi,
I think the greatest UI would contain a Search field where you could enter a text of XPATh and the Tree would expand all nodes matching the search and collapsing others.

Regards

**Pull request closed without merging**
