### PR TITLE
Bug 59281 testTimeDurationGUI

### PR DESCRIPTION
**Pull request by ra0077**
Hi,

There is a border in testTimeDuration.
It's not well integrated with the GUI of JMeter

I propose to remove the border

Antonio

### CODE REVIEW

**Comment by pmouawad** [comment]
I voluntarily made it like this because I found it more visible :-)
So I don't know what to do with this PR.

**Comment by ra0077** [comment]
Hi,

My opinion is that it's not well integrated with the JMeter GUI. I prefer before (like I have made it with my PR)

And because we don't must run laod test with the GUI, be visible is less important.

If you wan I can ask to a UX expert

Antonio

**Comment by pmouawad** [comment]
Hi Antonio,
I would be very interested by a UX Expert proposal on all JMeter GUI :-), not just this part.
This would really help us, provided the advice is not just, rewrite it all :-)

Thanks

**Comment by ra0077** [comment]
Hi Philippe,

I have ask to a UX Expert about this part (no time to audit all JMeter GUI)
I should have an answer next week

Antonio

**Comment by ra0077** [comment]
Need to find a better solution

Antonio

**Pull request closed without merging**
