### PR TITLE
Added Spock framework and some tests, both old and new

### PR DESCRIPTION
**Pull request by ham1**
## Description
WIP for adding Spock to JMeter. Created some new tests and translated some old ones.

## Motivation and Context
See the Mocking Framework email thread: http://mail-archives.apache.org/mod_mbox/jmeter-dev/201612.mbox/%3c36ce3782-dee8-388c-9539-5bcfb8d5f39a@internetallee.de%3e

## How Has This Been Tested?
By running the unit tests ;)

## Types of changes
- Dev enhancement

## Checklist:

- [x] My code follows the [code style][style-guide] of this project.
- [ ] I have updated the documentation accordingly.

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

### CODE REVIEW

**Comment by ham1** [comment]
Oh, failed due to tabs from isVar/PropDefined function patch.

**Comment by pmouawad** [comment]
Hi @ham1 ,
Thanks for this interesting PR.
There is a conflict in it, could you rebase it as you proposed.
Also, there is something I don't understand, I see coverage has decreased while you modified some existing tests and added new ones.
Maybe as a first step, you could only add new tests and not impact existing ones ?

Thank you
Regards

**Comment by ham1** [comment]
I've fixed any conflicts now.

So far I've migrated and added to:
* RunTime
* HTTPUtils

I've added new tests for:
* UniformRandomTimer
* JDBCSampler  - however I can't see how to test `sample()` due to  use of the inner class `DataSourceComponenetImpl` inside the `DataSourceElement.getConnection()`
*  `Top5ErrorsBySamplerConsumer` with some refactoring
* ` Top5ErrorsBySamplerData` and found a bug and fixed it here and #337 

Codecov hasn't posted again to the PR, but the coverage is now marginally higher: https://codecov.io/gh/apache/jmeter/pull/332

I will try to add some more tests over the next few days if this is useful? 

Also, I don't know much about ant and the way JMeter manages dependencies, so please let me know if there's a better way.

**Comment by ham1** [comment]
I've added some more tests:
* `ApdexSummaryConsumer` and 
* `ListResultData`

Plus some code tidy up.

Any thoughts?

**Comment by pmouawad** [comment]
Thanks @ham1 ,
I will have some time next week to merge it or this week-end.
If anybody wants to do that before he's welcome.
Thanks

**Comment by ham1** [comment]
Great, thank you. If someone could merge #337 first then I can make there are no conflicts.

**Comment by FSchumacher** [comment]
Thanks for your contribution.

**Comment by ham1** [comment]
Thank you for merging!

**Pull request closed without merging**
