### PR TITLE
Implement __StringToFile (Bug 63219)

### PR DESCRIPTION
**Pull request by ubikloadpack**
Hello,

The [UbikLoadPack](https://ubikloadpack.com) Team is happy to contribute the function __StringToFile as per:
https://bz.apache.org/bugzilla/show_bug.cgi?id=63219

It has been developed by Qian Qian Sha supervised by Philippe M.

Regards

## Description

This feature has been requested on Bugzilla under:

https://bz.apache.org/bugzilla/show_bug.cgi?id=63219

## How Has This Been Tested?

JUnits and tests in JMeter

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the [code style][style-guide] of this project.
- [X] I have updated the documentation accordingly.

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

### CODE REVIEW

**Comment by sebiboga** [comment]
Thanks for implementing this. What build will contain this feature?

**Comment by ubikloadpack** [comment]
Hello,
Any update on PR ?
Thanks

**Comment by ubikloadpack** [comment]
Merged through https://github.com/apache/jmeter/commit/d7c18c33b73cc91eb4063221fd5ada0e35bbf4fa

**Comment by ubikloadpack** [comment]
> Thanks for implementing this. What build will contain this feature?

Probably 5.2.
You can test nightly build tomorrow:

- https://ci.apache.org/projects/jmeter/nightlies/

 or jenkins last build:

- https://builds.apache.org/job/JMeter-trunk/lastSuccessfulBuild/artifact/trunk/dist/

**Comment by sebiboga** [comment]
It's working. Tested today on  r1857470.
Thank you very much!

**Pull request closed without merging**
