### PR TITLE
Mavenization

### PR DESCRIPTION
**Pull request by emilianbold**
I'm starting this pull request to get some feedback on the current changes.

Adding a Maven-based build system for JMeter implies moving and renaming some files and it would be best if we discuss this before I go too deep with customisations.

If you look at my commits, excluding the last one 'Add pom.xml files', they just rearrange files and update the changes in build.xml.

So, the plan is to still use ant, except on a Maven friendly file layout.

Note how I haven't moved the sources under src/main/java like Maven expects. I'm loading the sources from ./ but I would also like to move them. Each module (src/components, src/core, etc.) would get its own folder (src/components/src/main/java, src/core/src/main/java, etc).

As I've mentioned on the mailing list, I would also prefer to have all the modules at the same level. This means moving all the protocol/ftp, protocol/http modules a folder up, next to core and components/.

I'm able to load JMeter under Apache NetBeans and IntelliJ IDEA with the new Maven config so I am pleased with this as this is what was bothering me.

Replacing ant altogether is a big step but if we do it incrementally like I'm showing here by just preparing the file layout, etc. we can do it with less friction.

build.xml is 3600 lines long and can't easily be replaced all at once. I can imagine a transition period where ant will still be used for many targets, perhaps via the maven-antrun-plugin Maven plugin.

### CODE REVIEW

**Comment by FSchumacher** [comment]
Thanks for your work. I have just had a glance and will look into it as soon as I have a bit more time.
But I like the general direction, especially that we can (hopefully) migrate from ant to maven in small steps.

**Comment by emilianbold** [comment]
Any update on this? Most of the steps, like "Move resources to src/main/resources" are quite harmless and could be done at any time.

It's complicated to work on different branches when I have Maven only on one of them.

**Comment by pmouawad** [comment]
Hello @emilianbold ,
I think we should wait for 3.3 release , don't you think so ?

Regards

**Comment by emilianbold** [comment]
> I think we should wait for 3.3 release , don't you think so ?

I have checked to JARs to be identical so moving some files around while preserving the output seems safe.

Still, 3.3 is close, so it makes sense to have a code freeze.

**Pull request closed without merging**
