### PR TITLE
Bug60637 better statistics summary report

### PR DESCRIPTION
**Pull request by ra0077**

### CODE REVIEW

**Comment by ra0077** [comment]
Before

image

**Comment by ra0077** [comment]
After

image

**Comment by pmouawad** [comment]
Hello Antonio,
Thanks for PR.
My notes:
- I think you may have problems with your git config for end of line as your PR modifies more files than needed .

Regarding code, it looks ok to me.
I would just modify in dashboard.js.fmkr method 
`
         
createTable($("#statisticsTable"), ${statisticsSummary!"{}"}, function(index, item){
        switch(index){
            // Errors pct
            case 3:
                item = item.toFixed(2) + '%';
                break;
            // Mean
            case 4:
            // Percentile 1
            case 7:
            // Percentile 2
            case 8:
            // Percentile 3
            case 9:
            // Throughput
            case 10:
            // Received Kbytes/s
            case 11:
            // Sent Kbytes/s
            case 12:
                item = item.toFixed(2);
                break;
        }
        return item;
}, [[0, 0]], 0, summaryTableHeader);
`

**Comment by ra0077** [comment]
Hi Philippe,

Thanks to your feedback
I will integrate your modification.

If it's ok for all, I will modify the documentation and merge it

One question, do I need to modify the release note with a screenshot?

Antonio

**Pull request closed without merging**
