### PR TITLE
Added Shortcut key event for Reset search - 66053

### PR DESCRIPTION
**Pull request by rollno748**
## Description
Shortcut key to Reset Search

## Motivation and Context
This shortcut will help to Reset Search while enhancing or debugging the script 

## How Has This Been Tested?
Executed Unit test on core 
Validated the shortcut in local - works perfectly!

## Screenshots (if appropriate):
image

## Types of changes
* Adding Keyevent to enable shortcut for reset search functionality (non-breaking change which uses existing functionality)

## Checklist:
- [ ] My code follows the [code style][style-guide] of this project.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by rollno748** [comment]
@vlsi - can you please review and approve 
Its just a minor change in adding shortcut

**Comment by pmouawad** [comment]
Hello @rollno748 ,
Thanks for contributing.
Can you run ./gradlew autostyleApply and commit the result please ?

Thank you

**Comment by rollno748** [comment]
Thanks for reviewing it @pmouawad 
I have applied the autostyle and committed it

**Comment by vlsi** [comment]
Am I right the suggested shortcut is `ctrl+alt+f` to reset the search?
Does it come from a standard?

Have you considered using `esc` shortcut to reset the search?

**Comment by rollno748** [comment]
Yes the current shortcut is assigned to  ctrl+alt+f to reset the search.
I haven't considered the esc to set it as reset search.
I thought, It would be easier for us to remember to go with the same keys used to search (ctrl + f) -  with an alternate key added for reset 

Happy to hear your thoughts as well 
please advise !

**Comment by vlsi** [comment]
Frankly speaking, I think we should try using `ESC` shortcut for "resetting the search"

**Comment by rollno748** [comment]
Cool, Thanks for the inputs.
I will make that change and commit it.

**Comment by vlsi** [comment]
@rollno748 , thanks. For the next PR, please create a different branch. It is not a good idea to create PRs from `master` branch. For instance, in that case you won't be able to create two PRs at the same time.

**Pull request merged**
