### PR TITLE
Fix issue with annotation and implement remarks from last PR #246

### PR DESCRIPTION
**Pull request by max3163**
This PR fix a problem we encountered on the annotation metric : Field string have to be quoted and just escape ". 

I have taken your remarks into account and add the timestamp for each metrics and I use now the HttpAsyncClient. I add basic technical configuration too.

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello Maxime,
Thanks for being so active on JMeter these days ! I'm really happy about it.

I reviewed PR, it looks globally good except for something I don't understand.
Why do you use a CountDownLatch set to 1 ?
I think it is currently broken anyway as you only init once and countDown, so await will only "wait" the first time.

But anyway, in my understanding of AsyncHTTPCLient and our use case here, I think we can send without waiting, that's why I initially proposed to use Async. 
As we fill in timestamp, for me even if sending occurs in reverse order for whatever reason, it will not be a problem.

@Team, am I wrong ?
Thanks

**Comment by max3163** [comment]
Hello Philippe, 

My bad, you have totaly right. 
I push a new commit which remove the CountDownLatch. 
And with a little optimize of the timestamp usage.

**Comment by pmouawad** [comment]
Hello @max3163 , 
I merged this PR with following fixes/changes:
- Added more configuration on Async Http Client (Reactor)
- Fixed that End annotation not being sent
- Fixed the label in annotation containing "<timestamp>
- Restored back tags in annotation (is there any reason why you removed them in last PR ?)
- Isolated properties for this implementation and Graphite one
- Renamed properties.

Could you test in your environment and give feedback ?
Thank you for your work.

**Comment by max3163** [comment]
Hi,

In your implementation of annotations you add "Tags" as "Field" with the
same value as the the first tag.
I don't understand why you want to put this tag as field ?
If you realy want to have a tags, you could try like this :

events application=foo,tags=START,title=ApacheJMeter text="title test name
started"

and for the end :

events application=foo,tags=END,title=ApacheJMeter text="title test name
ended"



2017-01-21 11:10 GMT+01:00 Philippe M <notifications@github.com>:

**Comment by pmouawad** [comment]
Hello
I want something similar to that .
In next evolution, I think it would be useful to add tags as a parameter of the InfluxdbBackendListenerClient.
For example, users could set "Version 3.X.X of application" or "Load Test after pool tuning"....

Or maybe there's a better way I am not aware of.
[
screen shot 2017-01-21 at 23 10 48
]

**Comment by max3163** [comment]
You could have the same result in this way :

image

image

And I'm agree with you, in a next version, we could add tags as a parameter of the InfluxdbBackendListenerClient if you really want to have something different to application name.

**Comment by Wyatts** [comment]
Because InfluxDB makes a rather draconian distinction between "fields" and "tags" (and seemingly completely lacks the ability to convert either to the other _post hoc_), I'm going to suggest that the mechanism for controlling what gets sent as which is actually a fairly critical feature and one that I believe should ideally be relatively foolproof to work with.

On the GUI side of things, I envision a swaplist pre-filled with the common things that one might want to send as fields vs. tags.  Each side should allow additions to be made, and variables should be accepted.  (This probably lowers to a pair of CollectionProp in serialisation?)

**Comment by max3163** [comment]
Plse re-consider your last commit on the ANNOTATION side where you put tags as a field... 
Tags is a tag not a field.

**Comment by max3163** [comment]
I made some test on the last nigthly ( by the way, the apache-jmeter-r1780178.zip miss one librairie => httpcore-nio-4.4.6 ) 
When the test takes few second ( less than 5 second ) only the " ended " annotation is sending. 
I don't understand why ...

**Comment by pmouawad** [comment]
@max3163 , I've fixed the missing httpcore-nio.
For the bug, it's because you schedule every 5s, so test ends before and closes the Sender and just guarantees end is sent.
We could fix it but I'm not sure it's useful, why would anybody do a 5s load test ?

Regarding your note on Annotation, I don't understand why you want me to rollback. 
As I wrote, I think we should expose tags so that users can put whatever they want.
I didn't fully understand what @Wyatts  wrote but I think it's worth a discussion with all dev team before going further.

Regards

**Comment by max3163** [comment]
When we flush metrics in the teardownTest method, why the start annotations is not send too ? 

For my remark, I just want to put tags as tag and not as field. The user can put whatever he want too and it's more logic int influxdb sense to have Tags as tag.

I just propose this : 

influxdbMetricsManager.addMetric(EVENTS_FOR_ANNOTATION, TAG_APPLICATION + application + ",title=ApacheJMeter,tags=" + AbstractInfluxdbMetricsSender.tagToStringValue(tags) , 
                        "text=\"" +  AbstractInfluxdbMetricsSender
                        .fieldToStringValue(testTitle + " started") + "\"" );

And add a new parameter call tags as parameter of the backend.
If you are OK, I will push a new PR in this sense ?

I think it's important to let influxdb index this parameter (only tag are indexed ) and just keep the text value as field.

**Comment by pmouawad** [comment]
@max3163 ,
Ok for your proposal.

**Pull request closed without merging**
