### PR TITLE
Use a consistent bright color for splashscreen image

### PR DESCRIPTION
**Pull request by vlsi**
Before:

logo on dark background

After:

logo on light background

### CODE REVIEW

**Comment by vlsi** [comment]
@FSchumacher , do you have any idea on the way to display the logo with a dark background?

So far I'm inlined to enforce `#f2f2f2` background for the splash screen.

**Comment by weisJ** [comment]
Another possible solution would be to convert the image to svg and change the critical font colors based on the foreground of a `JLabel`. The font should be [this](https://fonts.google.com/specimen/Montserrat). Though I don’t know if this would violate the Apache [identity style guide](https://apache.org/foundation/press/kit/ApacheFoundation_StyleGuide.pdf).

**Comment by vlsi** [comment]
The logo is already in SVG: https://github.com/apache/jmeter/blob/master/xdocs/images/logo.svg

There's an alternative https://docs.oracle.com/javase/8/docs/api/java/awt/SplashScreen.html that might appear before any theme is actually loaded (== start with `java.awt.SplashScreen` and replace it with a more heavy-weight one later).

> critical font colors based on the foreground

The question there is to figure out the appropriate colors as well.
For instance, the platform default LaF might have an unpredictable background color, so it is not clear if there's a way to automatically select the font colors.

**Comment by weisJ** [comment]
> The question there is to figure out the appropriate colors as well.
> For instance, the platform default LaF might have an unpredictable background color, so it is not clear if there's a way to automatically select the font colors.

Shouldn’t it be safe to assume that the colour of a jlabel that is enabled/disabled can be read on its default background colour?

**Comment by vlsi** [comment]
> Shouldn’t it be safe to assume that the colour of a jlabel that is enabled/disabled can be read on its default background colour?

`Color bg = label.getBackground()` works.

What do you suggest for 

```java
Color apacheFgColor = ???;
Color jmeterFgColor = ???;
Color tmFgColor = ???;
```

I'm not a designer, but I doubt something like `255-R, 225-G, 255-B` would produce aesthetic results.

**Comment by weisJ** [comment]
I think the apache red should stay the way it is. Would need a really weird background to produce something that isn’t readable.
Then the colours could be:
````java
label.setEnabled(true);
Color jmeterFgColor = label.getForeground();
label.setEnabled(false);
Color tmFgColor = label. getForeground();
````

**Comment by vlsi** [comment]
I see what you mean.

I've created https://github.com/apache/jmeter/pull/565 as an alternative. The implementation is surprisingly simple thanks to `com.github.weisj.darklaf.icons.ThemedSVGIcon`.

**Pull request closed without merging**
