### PR TITLE
Bugfix: User Defined Variables are not evaluated on client (master) i…

### PR DESCRIPTION
**Pull request by markuswege**
## Description
Bugfix: https://github.com/apache/jmeter/issues/5896
 
User Defined Variables are not evaluated on client (master) in distributed setups. This has beed fixed by a second pass through the test tree after it is sent to the servers.

## Motivation and Context
We are using a distributed setup for our tests. Credentials and some configurations are passed via properties into the client (master). It occurred that the BackendListener, using User Defined Variables, received unevaluated strings as credentials (see bugticket linked for details).
In order to prevent side effects for test party running on the servers, we decided a second pass over the needed testelements after sending the unmodified test to the servers would be best.

## How Has This Been Tested?
Manual testing using debug logging.

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] My code follows the [code style][style-guide] of this project.
- [ ] I have updated the documentation accordingly.  

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

### CODE REVIEW

**Comment by vlsi** [comment]
Please keep `.idea/icon.png` intact.

**Comment by vlsi** [comment]
Do you think you could add a test case for the change?

**Comment by markuswege** [comment]
[Stripped.zip](https://github.com/apache/jmeter/files/11438767/Stripped.zip)

Testfile attached. To be run in distributed mode with 

`-JactiveProfileId=StrippedProfile -GactiveProfileId=StrippedProfile -Jpassword_influxdb_qat=PshYUe4Qsalv3G6Rywki3qT56CsLqcaN`

**Comment by vlsi** [comment]
Can you wrap it as batch test server test?

See https://github.com/apache/jmeter/blob/193bd552d492628e31b4c72bc2a5085ed0b14126/src/dist-check/build.gradle.kts#LL233C1-L233C1 , https://github.com/apache/jmeter/blob/193bd552d492628e31b4c72bc2a5085ed0b14126/bin/testfiles/BatchTestLocal.jmx

**Comment by markuswege** [comment]
Undestandable.
So, why are there no tests for ClientJmeterEngine?
Test coverage run in IntelliJ over all included tests show no coverage of ClientJMeter Engine or the according if-branch in PreCompiler.
If there were Tests, i would have added Testscases, but i simply don't have the time to create Tests for ClientJMeterEngine and PreCompiler from scratch.

**Comment by vlsi** [comment]
>So, why are there no tests for ClientJmeterEngine?

I have no idea.
It can be some tests are missing.
It can be the tests are executed from certain batch tests only.
It can be IntelliJ code coverage does not track tests spawned from batch tests because they execute JMeter as a custom subprocess, so they don't automatically inherit IntelliJ code coverage agent options.

---

>but i simply don't have the time to create Tests for ClientJMeterEngine and PreCompiler from scratch.

I understand what you say.
However, at the same time, I would mention that the code without tests is hard to maintain.

Imagine some time later I would start working on https://github.com/apache/jmeter/issues/5877
What would I do with the code you suggest in this PR? It would be hard to "just drop the code", however, it would be hard to understand if it still works as intended. That is one of the "maintenance overheads" we have.

The bug https://github.com/apache/jmeter/issues/5896 does not affect me directly, and I have no time for looking into it either.
So it would be great if you could reconsider and spend a little bit of time creating tests to cover your changes.
An alternative option might be waiting for somebody else to do it.
Thank you for understanding.

**Comment by markuswege** [comment]
After i while i refuse to write a test for this.
Why?
Because there is simply not a single test for the core classes. Few parts are covered indeirectly by tests.

Nevertheless, as you say: Hard to maintain, also hard to write tests for a pretty simple fix without any other tests doing some basic stuff like creating the TestTree from scratch.

Please either check manually or trust in our team programming efforts to fix this.

**Comment by vlsi** [comment]
> hard to write tests for a pretty simple fix without any other tests doing some basic stuff like creating the TestTree from scratch.

Please check https://github.com/apache/jmeter/blob/5bb56691f93bb7c6b6bee03a2f9a66a562199f51/src/components/src/test/kotlin/org/apache/jmeter/threads/openmodel/OpenModelThreadGroupConfigElementTest.kt#L39-L85

It creates the test tree from scratch.

**Comment by markuswege** [comment]
Note: We found a Workaround which was easier to implement as the tests for this fix ;)

**Pull request closed without merging**
