### PR TITLE
Display the result of the function when generate it

### PR DESCRIPTION
**Pull request by max3163**
A little modification to display the result of a generated function in the function helper panel.

### CODE REVIEW

**Comment by pmouawad** [comment]
Hi @max3163 ,
Interesting idea.
Does your implementation handle all functions ?

Thanks

**Comment by max3163** [comment]
Yes it handles all functions but work only if no context is needed ( like variables )

**Comment by pmouawad** [comment]
Hello,
It might be interesting to add some Text area to input some JSR223 Code to fill-in the context.

As a fist step, we should document this and possibly add a Hint that pops up to explain that test only works for function not relying on context.

Thanks

**Comment by max3163** [comment]
Sreenshot example : 
image

Any other feedbacks before merge it ?

**Comment by pmouawad** [comment]
Hi Mabye a SyntaxtTextArea for result would be better

**Pull request closed without merging**
