### PR TITLE
Reduced the size of all screenshots.

### PR DESCRIPTION
**Pull request by ham1**
## Description
Reduced size of all png screenshots using: `pngquant -f --ext .png --quality 70-95 *.png`.
Most were only reduced marginally but some were reduced a lot. This should probably be done for each new screenshot to ensure source control and the doc website loads as fast as possible.
Also: 
Removed workbench from a few screenshots.
Removed unused screenshots.

### CODE REVIEW

**Comment by FSchumacher** [comment]
Some of those images have been reduced already in the past. In my tests pngquant will happily compress those again, but that would probably be at 0.75*0.75 quality.

**Comment by ham1** [comment]
I've updated the PR:
* removed an unused screenshot
* de-duped a screenshot and
* compressed all png images with an individual saving of more than 2048 bytes using the command line and script below.

`find xdocs/ src/ test/ bin/ -iname "*.png" -print0 | xargs -0 -n 1 -P 3 ./compare-size.sh `

```bash
#!/bin/bash
set -e
err_report() {
    echo "Error on line $1"
    rm -v "${2}.new"
}
trap 'err_report ${LINENO} ${1}' ERR

pngquant --quality=70-100 --output "${1}.new" "${1}"

oldSize=$(stat -c%s "${1}")
newSize=$(stat -c%s "${1}.new")
let "diff = ${oldSize} - ${newSize}" || true # if sum is 0
let "threshold = ${newSize} + (1024 * 2)"

if [[ ${oldSize} -ge ${threshold} ]]
then
    echo "${1} compressed, saved ${diff}"
    mv "${1}.new" "${1}"
else
    rm -v "${1}.new"
fi
```

**Comment by ham1** [comment]
Deleted the wrong branch...

**Comment by pmouawad** [comment]
Hi Team,
if there are volunteer to merge this one, thanks in advance.
Regards

**Pull request closed without merging**
