### PR TITLE
Checks for listener output file existence

### PR DESCRIPTION
**Pull request by max3163**
Before launch a test ( local or remote ) check existence of result file from all collectors listeners and ask to the user what he want to do :
 - Don't start the test 
 - Append result to the file ( old default behaviour) 
 - replace the file 

For non gui mode, a new param/option has been created ( i.e -f or --forceDeleteResultFile ) in order to replace all results files. If no option is indicated on the command line, the old behavior is retained

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello,
I reviewed this PR and I have some blocker remarks so I didn't merge it:
- I think code in StandardJMeterEngine  and DistributedRunner is duplicated
- I wouldn't put any dependency on java.awt in those 2 classes.
- deleteResultFile should not be static but I don't know how to make it better

Regards
Philippe

**Comment by max3163** [comment]
I move and refactoring the code on the gui.action package. Where it's seem more logic.
What do you think about it Philippe ?

**Comment by max3163** [comment]
Don't look the 331f476 commit, weird issue on my side, sry.

**Comment by pmouawad** [comment]
Hi Maxime, 
Is the PR ok now ?
Thanks

**Comment by max3163** [comment]
I have fix all your remark : 

- Refactoring code
- Move the popup in the  gui.action package
- deleteResultFile is no more static and just in JMeter.java

This PR is now OK for me.

**Comment by pmouawad** [comment]
Hi @max3163 ,
As you're a commiter now, could you apply it ?
I tried to but it seems the generated patch files contains other files (JSONManager) , I don't know why but there seem to be unrelated commits.

Thanks

**Comment by pmouawad** [comment]
Merged with commit:
http://svn.apache.org/viewvc?rev=1783297&view=rev

This PR can be closed.
Thanks

**Pull request closed without merging**
