### PR TITLE
Refactoring of HTTPSamplerBase

### PR DESCRIPTION
**Pull request by ham1**
Removal of unused method.
Minor simplifications of some boolean expressions.
Code formatting.
Spelling.

I've split the removal of the method and the formatting + simplification into 2 commits, hopefully this is better than 1 commit or 2 PRs?

### CODE REVIEW

**Comment by pmouawad** [comment]
Hi,
At Team, Please avoid merging this PR for now as it would introduce a conflict on :
https://bz.apache.org/bugzilla/show_bug.cgi?id=59033

which is more important in terms of code volume.
Merging this one afterwards will be easier.
Thanks

**Comment by pmouawad** [comment]
Hello,
Thanks for PR.
Would it be possible to either resubmit it after 3.0 release or resubmit one updated ?

Thanks

**Comment by FSchumacher** [comment]
I applied all of your formatting, typo and boolean expression changes (I think). The change of APPLIABLE to APPLICABLE seems correct, but that mistake is in all classes, that use this word, so I left it.
I wonder if we should deprecate the unused method, in favour of deleting it, since it could be used by someone else.

**Comment by ham1** [comment]
@FSchumacher thank you for applying most of my changes. I've updated the PR and there are a few more minor things left. Regarding the spelling of that constant, I agree, it's probably better to be slightly wrong but consistent than inconsistent.

Regarding the delete vs. deprecate, deprecation is probably a good first step, but as it's a protected method and it's not used in any of the subclasses it seems unlikely that someone is using it?

Thanks

**Pull request closed without merging**
