### PR TITLE
add negate ifcontroller 5994

### PR DESCRIPTION
**Pull request by anasoid**
## Description
Add negate checkbox to ifcontroller
Related to #5994 

## Motivation and Context
it's an easy way to have if else by duplicating ifcontroller and check negate and in many case the negate value is more clear than real condition

## How Has This Been Tested?
Test are added to TestIfController.java to test :
1. default value not change the result (send sample)
2. negate true will not send sample
3. negate false will send sample

## Screenshots (if appropriate):

image

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist:

- [ x] My code follows the [code style][style-guide] of this project.
- [ x] I have updated the documentation accordingly.

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

### CODE REVIEW

**Comment by vlsi** [comment]
Thanks for working on this, however, I would rather approach https://github.com/apache/jmeter/issues/5981 first. I am afraid adding checkboxes like "invert" would make UI even more complicated.

**Comment by anasoid** [comment]
Agree #5981 will be more powerfull and easy to use

**Comment by vlsi** [comment]
Should this PR and the issue be closed then?
Do you think you could work on https://github.com/apache/jmeter/issues/5981?

**Comment by anasoid** [comment]
yes we can close this PR and issue.
I can work on #5981

**Comment by vlsi** [comment]
Closing in favour of https://github.com/apache/jmeter/issues/5981

**Pull request closed without merging**
