### PR TITLE
Bug 59934

### PR DESCRIPTION
**Pull request by jloisel**
Fix CssParser race condition and poor concurrency level by using Guava's LoadingCache.

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello @jloisel ,
Thanks for your contribution.
I agree with your analysis of "race condition" and it impact on performances.

But do you have some benchmark that shows the improvement in performances related to the usage of Guava here ? 
Can't the patch be written without it ?

I just want to be sure we absolutely need to introduce guava dependency.

Thanks

**Comment by jloisel** [comment]
I don't have benchmark. But, according to "Java Concurrency in Practice" in section "11.5 Example: Comparing Map performance", ConcurrentHashmap performs a lot better (up t o 40x faster) than Synchronized map when multiple threads are contented on a single resources.

Here is an extract from the book:

> The major scalability impediment for the synchronized Map implementations
is that there is a single lock for the entire map, so only one thread can access the
map at a time. On the other hand, ConcurrentHashMap does no locking for most
successful read operations, and uses lock striping for write operations and those
few read operations that do require locking. As a result, multiple threads can
access the Map concurrently without blocking.

Synchronized map uses a single lock both for reads and write, contending even read-only threads between each other. On the other side, ConcurrentHashMap uses lock stripping and is contention free between reader threads. 

Guava's LoadingCache makes the code easy to understand, easy to maintain and is fast. You can probably be able to write your own cache without guava, but it's hard to implement something both easy to use and efficient in a multithreaded environment.

Guava is the 3rd most popular Java library behind JUnit and SLF4J, i'm actually quite surprised it's not part of JMeter until now:
[The Top 100 Java Libraries in 2016](http://blog.takipi.com/the-top-100-java-libraries-in-2016-after-analyzing-47251-dependencies/)

**Comment by pmouawad** [comment]
@jloisel , my note was not on using ConcurrentHashmap :-) (I am aware of this), 
but on the usage of Guava.

Ok thanks for feedback, I'll commit the PR after further review

**Comment by vlsi** [comment]
>Ok thanks for feedback, I'll commit the PR after further review

+2MiB of dependencies :)

**Comment by pmouawad** [comment]
@vlsi, that was my main concern but @jloisel  convinced me, if you have a better option without guava , feel free to amend PR.
Shall I wait or do I commit ? 
For now I may not commit the change to URLCollection, only the rest.

**Comment by vlsi** [comment]
Re guava: AFAIK, if guava is included into JMeter, then it might clash with plugins that also want guava.
AFAIK, guava is known to break backward compatibility quite often, so it might trigger "jar hell" kind of issues.

**Comment by vlsi** [comment]
Regarding "fast cache with limited size", there's 
https://github.com/ben-manes/concurrentlinkedhashmap

It is 120 KiB jar with very little possibility to break backward compatibility ever.

**Comment by pmouawad** [comment]
@vlsi regarding guava compatibility:
http://stackoverflow.com/questions/21867295/is-guava-binary-compatible-with-previous-versions


Regarding your proposal, there is only 1 contributor to this library, so I am not a fan.
If there's a nogo for guava, I prefer that we just use ConcurrentHashmap then.

**Comment by vlsi** [comment]
>regarding guava compatibility:

Regarding "guava usage in Apache Calcite project": https://issues.apache.org/jira/browse/CALCITE-1325

>We were incorrect to state that Calcite release 1.8 works with "Guava versions 12.0.1 to 19.0"; it should state "Guava versions 14.0 to 19.0".
>Calcite release 1.7 and earlier do not have this problem.

And so on. The idea is JMeter releases are very rare, and I do not like the idea of making guava a yet another reason to make "urgent compatibility releases".

>Regarding your proposal, there is only 1 contributor to this library, so I am not a fan.

The idea is there is no need to improve the library. All the bugs are resolved long ago, so CLHM serves its purpose well.

CLHM is superseded by https://github.com/ben-manes/caffeine (java8 only) cache.

>I prefer that we just use ConcurrentHashmap then.

CHM has no way to evict old entries, thus if using just CHM, there would be a risk of running out of memory (e.g. when CSS resource URLS are dynamically generated). I do not like exposing JMeter users to OutOfMemory conditions.

**Comment by vlsi** [comment]
https://issues.apache.org/jira/browse/CALCITE-736

>Guava is involved in major dependency hells in Java, with Hadoop the most affected ecosystem.
>Removing Guava types from visible parts of Calcite API will help containing damage to backwards compatibility if/when, at some point, shading needs to be done.

**Comment by FSchumacher** [comment]
I like the idea of the smaller library (cache) instead of rushing into guava for this use case only.

**Comment by pmouawad** [comment]
>The idea is JMeter releases are very rare, 
This is supposed to change :-)

>CHM has no way to evict old entries, ...
I hope you don't think I ignore that :-) What I mean is create an LRU based on CHM

Another option would be to move to Java 8 and use caffeine directly (1mb).

**Comment by jloisel** [comment]
Guava is highly stable and mature now, incompatible changes are unlikely to happen. +2MiB of dependencies being added? It's nothing today. Groovy alone takes 7.0MiB in JMeter. Guava is also already used by JMeter Plugins like Webdriver, which also uses Guava 19.0. It's up to JMeter plugins developers to keep up-to-date their plugins, and up to JMeter developers to keep internal libraries up-to-date.

Calcite is a database framework whose purpose is to be integrated into java applications. This is not the general case for JMeter. Problems with dependencies depend on the usage of the library itself.

Caffeine is probably a great caching library which deserves to be used, but it's its only usage. Guava is a multi-purpose library. It has so many interesting libraries like high performance immutable collections, String Joiners and Splitters, Comparable/Comparator made simple through Ordering, Multimaps, Ranges, great hashing algorithms like MurMur, Preconditions and more. 

Generally speaking, caches should be avoided at all cost as Martin Fowler said:
> There are only two hard things in Computer Science: cache invalidation and naming things.
[http://martinfowler.com/bliki/TwoHardThings.html](http://martinfowler.com/bliki/TwoHardThings.html)

:+1: for a migration to Java 8 too, as it would allow to use built-in Streams, Function, Predicate and more.

**Comment by vlsi** [comment]
>What I mean is create an LRU based on CHM

That is basically what CLHM does. So I would pull CLHM and save our resources for something more valuable than "implementing yet another CHM-based cache for CSS".

> Another option would be to move to Java 8 

I'm not sure it is in scope of the current bug id.

Migrating to Java 8 would be indeed nice.

**Comment by vlsi** [comment]
> like Webdriver, which also uses Guava 19.0

That basically means if newer Webdriver would use Guava 20, that might render "newer webdriver incompatible with older JMeter". That is exactly one of the reasons I'm hesitant to pulling Guava in.
Current case when "Guava is not used by JMeter itself" makes it more flexible for the plugins to use whatever version they like (unless the plugins do not clash with each another)

> jloisel: String Joiners and Splitters

Lots of those has native Java8 classes. I do not say Java 8 makes Guava completely obsolete, however we'd consider each added dependency.

> great hashing algorithms like MurMur

Note: JMeter needs high-performant algorithms, so instead of Guava's MurMur I would use https://github.com/OpenHFT/Zero-Allocation-Hashing

**Comment by vlsi** [comment]
>jloisel: Calcite is a database framework whose purpose is to be integrated into java applications

JMeter's purpose is to be integrated with various plugins, so exposing extra core dependencies is not that good.

I'm not sure if we could use OSGi-like approach so "JMeter core" and "plugins" could use different versions of the same library.
That might be good in a long run, however it is not implemented AFAIK.

**Comment by vlsi** [comment]
> jloisel: Groovy alone takes 7.0MiB

Do you have better language for JSR232 in mind?
The thing is beanshell is outdated, and Nashorn JS is not yet very popular.

In other words: building Groovy in would be visible to end-users. They would benefit from simplified usage of Groovy in JMeter.
On the other hand, if we integrate Guava, then end-users would notice nothing (Guava has nothing to do for day-to-day JMeter usage), except "increased download size".

**Comment by jloisel** [comment]
> That basically means if newer Webdriver would use Guava 20, that might render "newer webdriver incompatible with older JMeter". 

Well, in 2.13 webdriver plugin was already breaking JMeter by using HttpClient 4.5.2 while JMeter was using 4.2.6. The solution to dependency problem is not to not use any dependency at all. What if you write everything by yourself? You end up maintaining a lot more code, and probably less well written than someone who wrote and maintained a library doing this for years.

> JMeter needs high-performant algorithms

First make it right, then make it fast. Stop optimizing all the time. Optimization comes with a major trade-off, code complexity. Hashing is surely not the bottleneck in JMeter overall performances.

> On the other hand, if we integrate Guava, then end-users would notice nothing (Guava has nothing to do for day-to-day JMeter usage), except "increased download size".

Sure, downloading 2MiB of additional dependencies adds exactly 1 sec with a standard 20Mbits DSL connection. commons-math3 takes 2.2 MiB and is being used by exactly 4 classes in JMeter. Should we write the statistics computation from scratch to save those 2MiBs? Hell no.

> In other words: building Groovy in would be visible to end-users. On the other hand, if we integrate Guava, then end-users would notice nothing.

This is the kind of reasoning which made me leave a software company. Refactoring was considered not adding any value for the end user. Needless to say they are unable to maintain the product anymore today.

When using a library written by somewhere else which does the job for you instead writing the code yourself, it's like "hiring someone to do the job for you". And He takes care of maintaining that stuff, instead of you.

**Comment by vlsi** [comment]
> Hashing is surely not the bottleneck in JMeter overall performances.

Why do you think synchronized CSS cache is the bottleneck then?

**Comment by vlsi** [comment]
> commons-math3 takes 2.2 MiB and is being used by exactly 4 classes in JMeter. Should we write the statistics computation from scratch to save those 2MiBs? Hell no

That is a nice finding.
We might want to replace commons-math3 with https://github.com/HdrHistogram/HdrHistogram

**Comment by vlsi** [comment]
>Refactoring was considered not adding any value for the end user.

The problem with adding extra dependencies to core is not "JMeter will get harder to maintain"
The main problem (from my point of view) is that typical end-users of JMeter have little to do with Java programming. They have little idea what "NoSuchMethodError" is, and so on.
So, I think in a long run it makes sense to reduce possibility of running into "plugin X is not compatible with plugin Y when deployed to JMeter version Z" kind of errors.

**Comment by julianhyde** [comment]
For the record, regarding https://issues.apache.org/jira/browse/CALCITE-1325. That was not an example of "JAR hell". Calcite attempts to maintain compatibility with a wide range of Guava versions and that was a case where our QA process screwed up and we slipped a little. To date no one has ever said "I can't use Calcite because you require Guava X and we use Guava Y".

**Comment by jloisel** [comment]
> Why do you think synchronized CSS cache is the bottleneck then?

I saw a race condition in the existing implementation and fixed it following the [Boy scouts principle](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule). It's simply not working properly: the CPU can go crazy if the cache is full when many virtual users are executing. If the requirement is that the code doesn't need to work, then sure, I can make an implementation that gives instant results.

Anyway, I'll be okay with any decision being made, I'm not getting any reward for pushing Guava inside JMeter :+1:

**Comment by pmouawad** [comment]
Let's not diverge too much :-)
1. I opened a discussion threads on dev mailing list on Java8 migration.
2. @vlsi  OSGI approach is a huge & complex piece of work, frankly I doubt we do it knowing all the other more important things we have on roadmap and that do not make any progress.
3.@vlsi , regarding hashing, can you clarify what you mean in a separate dev discussion ?
4. Regarding JMeter-Plugins/Webdriver, I am not sure we must consider this, it already happened with httpclient dependency. It could happen with a lot of jmeter deps.
5. HdrHistogram should be another discussion, related to CO issue for example on which we discussed a lot without making much progress
6. @vlsi , if you want CLHM, why not propose a PR implementing PR-221 with it ? or do you prefer to wait for decision on guava or not guava ?

**Comment by vlsi** [comment]
>if you want CLHM, why not propose a PR implementing PR-221 with it ? or do you prefer to wait for decision on guava or not guava ?

I prefer to wait an agreement first, since the code is simple for both cases.

**Comment by vlsi** [comment]
> OSGI approach is a huge & complex piece of work, frankly I doubt we do it knowing all the other more important things we have on roadmap and that do not make any progress.

Alternative solution would be to repackage guava (or whatever), so JMeter uses its own org.apache.jmeter.guava...

I do understand that OSGi-like approach is a no way a quick-win.

**Comment by ben-manes** [comment]
> There is only 1 contributor to this library, so I am not a fan.

Please note that CLHM was the precursor to Guava's Cache. While now dormant, its robustness can be attested to by many projects such as Cassandra, Grails, and Neo4j. Due to its small size, many opted to shade it such as Camel, Apache Cayenne, and OmniFaces.

But its purely an LRU cache using the Map interface. Features like expiration, self-populating, etc. were delegated to decorators. This was because a concurrent LRU is surprisingly hard due to every read modifying global state, so it took 2 years of experiments before stumbling on the right ideas. Then Guava took advantage to push the feature envelope and provide a complete caching abstraction.

Guava does have a good deprecation strategy (min 2 years notice). However Hadoop has a poor dependency strategy due to running user supplied jars within its classloader. This lack of isolation causes users to blame Guava, though shading (either by Hadoop or user's) would be an easy resolution.

If you're debating between CLHM, Guava, or Caffeine then you'll probably end up having any bugs fixed by the same developer. Though hopefully by now they've all had enough usage to smooth out the issues.

**Comment by pmouawad** [comment]
@ben-manes , thanks for those clarifications and your work on CLHM and caffeine, very interesting.

**Comment by pmouawad** [comment]
Hello,
I'll wait 2 more days for reaction on guava subject.
Unless there is a nogo, I'll commit the patch as is.
Regards

**Pull request closed without merging**
