### PR TITLE
Update mongo-java-driver version

### PR DESCRIPTION
**Pull request by IgorSasovets**
## Description
- changed mongo-java-driver version to 3.8.0;
- updated LICENSE file;

## Motivation and Context
Hi, Team! I wanted to test my application that uses MongoDB database using JMeter but faced with problems which related to mongo-java-driver version. Since MongoDB config deprecated, I used JSR232 Sampler and wrote Java code that allows me to interact with database. Current version of mongo-java-driver (2.11.3) is out of date and I couldn't connect to my DB using created script. So, I decided to update mongo-java-driver version because it allows to use JMeter with MongoDB and has big impact to user experience (at least, for me and my colleagues).

## How Has This Been Tested?
I tested it locally on my machine using ant test command. 

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the [code style][style-guide] of this project.
- [x] I have updated the documentation accordingly.

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

### CODE REVIEW

**Comment by FSchumacher** [comment]
Thanks for your contribution, but I don't think this is the correct solution.
If we only update the jars, the code will not compile anymore. There are a lot of missing and deprecated methods and classes. I tried to update our usage of the api to the current one, but that is not possible without a lot of work. (The authentication mechanism has changed and the eval mechanism, that we depend on has been deprecated/removed).
As the mongo sampler has been deprecated with JMeter 3.0. So a better patch would be to remove the client jars altogether.

**Comment by FSchumacher** [comment]
When I compile your PR with ```ant download_jars clean install```, I get the following:
```
compile-mongodb:
    [javac] Compiling 9 source files to /xxx/jmeter/build/protocol/mongodb
    [javac] /xxx/jmeter/src/protocol/mongodb/org/apache/jmeter/protocol/mongodb/config/MongoSourceElement.java:117: error: cannot find symbol
    [javac]                 .autoConnectRetry(getAutoConnectRetry())
    [javac]                 ^
    [javac]   symbol:   method autoConnectRetry(boolean)
    [javac]   location: class Builder
    [javac] /xxx/jmeter/src/protocol/mongodb/org/apache/jmeter/protocol/mongodb/config/MongoSourceElement.java:130: error: no suitable constructor found for WriteConcern(int,int,boolean,boolean,boolean)
    [javac]             builder.writeConcern(new WriteConcern(
    [javac]                                  ^
    [javac]     constructor WriteConcern.WriteConcern() is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(int) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(String) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(int,int) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(boolean) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(int,int,boolean) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(int,int,boolean,boolean) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(String,int,boolean,boolean) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor WriteConcern.WriteConcern(Object,Integer,Boolean,Boolean) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac] /xxx/jmeter/src/protocol/mongodb/org/apache/jmeter/protocol/mongodb/mongo/MongoDB.java:53: error: cannot find symbol
    [javac]         boolean authenticated = db.isAuthenticated();
    [javac]                                   ^
    [javac]   symbol:   method isAuthenticated()
    [javac]   location: variable db of type DB
    [javac] /xxx/jmeter/src/protocol/mongodb/org/apache/jmeter/protocol/mongodb/mongo/MongoDB.java:57: error: cannot find symbol
    [javac]                 authenticated = db.authenticate(username, password.toCharArray());
    [javac]                                   ^
    [javac]   symbol:   method authenticate(String,char[])
    [javac]   location: variable db of type DB
    [javac] /xxx/jmeter/src/protocol/mongodb/org/apache/jmeter/protocol/mongodb/sampler/MongoScriptRunner.java:55: error: cannot find symbol
    [javac]         db.requestStart();
    [javac]           ^
    [javac]   symbol:   method requestStart()
    [javac]   location: variable db of type DB
    [javac] /xxx/jmeter/src/protocol/mongodb/org/apache/jmeter/protocol/mongodb/sampler/MongoScriptRunner.java:57: error: cannot find symbol
    [javac]             db.requestEnsureConnection();
    [javac]               ^
    [javac]   symbol:   method requestEnsureConnection()
    [javac]   location: variable db of type DB
    [javac] /xxx/jmeter/src/protocol/mongodb/org/apache/jmeter/protocol/mongodb/sampler/MongoScriptRunner.java:66: error: cannot find symbol
    [javac]             db.requestDone();
    [javac]               ^
    [javac]   symbol:   method requestDone()
    [javac]   location: variable db of type DB
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 7 errors
```
That means, that the current code doesn't work with the new jars.

If you want to update the code the new jars, go ahead, but as of JMeter 3.0 the sampler has been deprecated and it should have been removed with version 3.1 (which obviously didn't happen).

It would be interesting to see your JSR223 sampler. I suspect it handles all of the connection setup and client usage itself. Maybe it would be a good idea to discuss your use case and solution on the mailing list.

**Comment by IgorSasovets** [comment]
Thanks for support! I tested my changes using ant download_jars command and didn't get any errors. I think we should continue our discussion. How I can mail you?

**Comment by FSchumacher** [comment]
You can reach me (and other JMeter users/developers) on the [JMeter mailing list](https://jmeter.apache.org/mail2.html#JMeterDev)

I hacked together an updated version of the Mongo Sampler at https://github.com/FSchumacher/jmeter/tree/pr-390-mongo, but I am not sure, that it is a good idea, as it will break all old test plans.

And note, that I don't use MongoDB, so I am not sure, if it is correct at all.

**Comment by pmouawad** [comment]
Hi Felix,
My opinion is that if you did the upgrade it’s ok to break old plan provided we clearly state we did this.

It is fair that we upgrade now a very old version of MongoDB API and drop deprecated code.

I think we had some complaints about this very old driver version, missing new auth methods both on mailing list and surely on stackoverflow.

So it will be a good thing to upgrade. 
Regards

**Comment by undera** [comment]
Maybe revive old idea of extracting MongoDB components into external plugin? Custom plugin detaches version from core JMeter, which means some users can use older version of plugin, while rest of JMeter can be upgraded to newer.

**Comment by IgorSasovets** [comment]
@FSchumacher, I can try your updates and provide feedback. Also, please provide your Java and ant versions. Maybe this caused errors during build process.

**Comment by FSchumacher** [comment]
I always build with Oracle JDK 8 (u171 at the moment). ant version is 1.10.3. 
I suspect that you have an old mongo db jar lying around in your build path.

**Pull request closed without merging**
