### PR TITLE
Use SVG icon for splashscreen

### PR DESCRIPTION
**Pull request by vlsi**
This change makes the image look better in macOS 2x resolution (e.g. compare the screenshots with https://github.com/apache/jmeter/pull/563 ).

I'm not sure we need `.png` logo in case we use `.svg`.

IntelliJ:
intellij

Darcula:
darcula

SolarizedLight:
solarizedLight

SolarizedDark:
solarizedDark

System (macOS):
system_mac

Motif:
motif

Nimbus:
nimbus2

Metal:
metal

Fallback (in case svg resource is not found):
fallback_logo

### CODE REVIEW

**Comment by vlsi** [comment]
Just in case:

* `Label.disabledForeground`.  It is missing in Nimbus (darklaf converts it to red), and it is white in Motif

* `textInactiveText`: missing in Nimbus.

* `ComboBox.disabledForeground`: missing in Nimbus. It has a strange color in Metal.

* `Button.disabledText`: missing in `Motif`

So far it looks like there's no color name that could be used universally for "disabled label foreground".

@weisJ, what do you think if a fallback was added to `IconColorMapper` so it could try multiple colors?
Something like "try `Label.disabledForeground`, if missing try `textInactiveText`, if missing try` Button.disabledText` if missing try `Label.foreground`, otherwise use `#ff0000`"?

**Comment by weisJ** [comment]
I have added the option to add fallback keys. They are declared in the `LinearGradient` with `fallbackKeys="key1,key2,key3,..."`. You can try it out with the current `master` branch of darklaf. The id is still the prioritised key.

**Comment by vlsi** [comment]
Technically speaking, you've implemented

```xml
    <linearGradient id="Label.disabledForeground"
                    style="fallback:textInactiveText Button disabledText">
      <stop offset="0" stop-color="#4d4d4d"/>
      <stop offset="1" stop-color="#4d4d4d"/>
    </linearGradient>
```

**Comment by weisJ** [comment]
It would be:
 ```xml
<linearGradient id="Label.disabledForeground"
                 fallbackKeys="textInactiveText,Button.disabledText">
    <stop offset="0" stop-color="#4d4d4d"/>
    <stop offset="1" stop-color="#4d4d4d"/>
</linearGradient>
```

**Comment by vlsi** [comment]
Just in case: I've actually tried, and `fallbackKeys="textInactiveText,Button.disabledText"` does not really work.

There's no `keys` in https://github.com/weisJ/darklaf/commit/e117205b5b7bf22ef4811a54aa9213dcb8db2341#diff-20761adcf666eb958134331292e43dacR96

**Comment by weisJ** [comment]
Yeah I changed it and forgot about it.

**Comment by vlsi** [comment]
There's about window as well:
jmeter_about

I guess should be updated as well

**Comment by vlsi** [comment]
IntelliJ

about_light

Darcula:

about_dark

**Comment by vlsi** [comment]
So far it looks good to me, will commit if there are no objections.

**Pull request merged**
