### PR TITLE
Bug 63255 - HTTP Post Request fails due to triple backslash in Body Data

### PR DESCRIPTION
**Pull request by jloisel**
## Description
Fix bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=63255

## How Has This Been Tested?
Tested manually.

## Types of changes
- Bug fix (non-breaking change which fixes an issue

## Checklist:
- [x] My code follows the [code style][style-guide] of this project.
- [ ] I have updated the documentation accordingly.

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

### CODE REVIEW

**Comment by jloisel** [comment]
The fix is probably not adequate, since it breaks other parts of JMeter. But it's impossible to use JMeter in the case you have escaped json in POST request data with variables within.

**Comment by pmouawad** [comment]
Thanks for PR, but as you can guess, it cannot be merged without:

- Existing tests passing
- Additional tests for this particular case

If you can update the PR, it would be nice.
Thanks

**Comment by jloisel** [comment]
Hi Philippe, Thanks for reviewing this pull request. Do you have any idea on how to fix both the issue (do not escape remove escapes from escaped json, which relies on `\`) and support escaping `\`? I may have missed something. 

I thought about splitting the method to have both old and new behavior, depending on the context.

One thing is sure, replacing `\\` by `\` when the content contains a variable is causing issues as it alters the content of the request.

**Comment by pmouawad** [comment]
Hello @jloisel ,
Your approach of splitting looks a good approach to me.
Thanks for contributing.
Regards

**Comment by pmouawad** [comment]
Hello,
I'll close PR as it is not mergeable currently.

Thanks
Regards

**Comment by jloisel** [comment]
No problem. I didn't find any good approach to solve this issue as of now. Even splitting into multiple methods doesn't seem an easy task, given how low level this code is.

**Pull request closed without merging**
