### PR TITLE
Fix to 61071

### PR DESCRIPTION
**Pull request by alekseibalan**

### CODE REVIEW

**Comment by abalanonline** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=61071

**Comment by pmouawad** [comment]
Hello @abalanonline ,
Thanks for your PR.
Would it be possible to provide a current failing test case that shows the issue and confirms that your fix is ok ?

Thank you

**Comment by abalanonline** [comment]
Hello @pmouawad ,
Test case provided.
There are errors in build. Failed to resolve host name: jmeter.apache.org

**Comment by pmouawad** [comment]
Thanks for completing the PR.
Percentile 50 should be equal to median. 
So I suspect the bug is in getPercentPoint().

I wonder if it's not occasion to switch to https://github.com/HdrHistogram/HdrHistogram

**Comment by abalanonline** [comment]
There are two methods for calculating percentile: Nearest Rank method and Linear Interpolation Between Closest Ranks method.
Median equal to percentile 50 if interpolation method is used. But for JMeter measuring purposes the nearest rank percentile should be used because perc 90 gives the exact maximum time for 90% of tests and this is what JMeter users are expecting.
This is why the median should be calculated separately (or we can implement interpolation method and use it for particular median purpose).
By the way getPercentPoint method is [failing also](https://gist.github.com/abalanonline/9b128faa67e2459b765c1ef56454684b). I will raise a bug.

**Comment by abalanonline** [comment]
Hello @pmouawad ,
I investigated the HdrHistogram project. Unfortunately we cannot use it in JMeter right now.
1. It do not have median method implemented.
2. It do not have the interpolated percentile method either.
3. It have the same bug calculating the 75th percentile of 11 data values {3, 6, 7, 8, 8, 9, 10, 13, 15, 16, 20} (example from Wikipedia)
So I suggest either fix the bugs in current org.apache.jorphan library. Or implement the necessary methods (and fix the bug) in HdrHistogram and after that use it in JMeter.
I provided two pull requests in case you prefer a quick solution.

**Comment by pmouawad** [comment]
Hi Team,
What shall we do ?
As per Felix note on dev mailing list, it is more an algorithm variation than a bug.

**Comment by vlsi** [comment]
Note: this PR was automatically closed when JMeter development moved from SVN to Git (main branch was renamed from `trunk` to `master`, thus GitHub closed the PR).
If you want to revive the PR, please update your fork as per https://github.com/vlsi/jmeter-git-cleanup/tree/v2.2.0/clean_fork , reopen the PR (unfortunately, it has to be a new PR).

If you have questions, please feel free to ask on JMeter dev list.

Sorry for the inconvenience

**Pull request closed without merging**
