### PR TITLE
MQTT plugin for Jmeter

### PR DESCRIPTION
**Pull request by hemikak**
Hi All,

This PR contains a 'Publisher' and 'Subscriber' sampler for MQTT(Message Queuing Telemetry Transport) v3.1.1 protocol. Specification at [1].  The samplers use the Eclipse Paho MQTT client v1.0.2 for publishing and subscribing.

The client was tested on WSO2 Message Broker.

Your comments are welcomed.

[1] - http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

Thanks,
Hemika

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello,
First , big thanks for your PR.
We will have a look at it soon, but if teams agrees on integrating it to Core, it should happen in N+2 release (not the next one).

Taking into account the size of contribution, I think you should send a http://www.apache.org/licenses/icla.txt to secretary at apache.org mentioning this contribution.

Thanks a lot again.
Regards
Philippe M.
@philmdot

**Comment by hemikak** [comment]
Hi @pmouawad ,

I received an acknowledgement on the ICLA.

Regards,
Hemika

**Comment by hemikak** [comment]
Sampler images : 

mqtt_subscriber
mqtt_publisher

**Comment by hemikak** [comment]
Hi @pmouawad ,

Any update regarding the PR ?

Regards,
Hemika

**Comment by pmouawad** [comment]
Hi,
As I said, for nowwe are preparing the next version. This sampler if acceptedby team would be in n+2 version.
I have opened a dev discussion regarding its integration. 
You can follow and comment on dev mailing list.Regards

**Comment by hemikak** [comment]
Hi All,

I updated the PR to resolve merge conflicts. Also updated the mqtt paho client library version to 1.1.0.

Regards,
Hemika

**Comment by pmouawad** [comment]
It appears that you have made this a 3rd party plugin for MQTT.
So we'll close this PR as WONTFIX.

Thank you anyway for your contribution.

**Pull request closed without merging**
