### PR TITLE
Bug 59937: Sub menus addition

### PR DESCRIPTION
**Pull request by vherilier**
JMeter must offer developers to place elements in sub-menus too to improve the user experience.

It is realised by introducing the "drawer" property into "MenuInfo".
The "MenuFactory" uses this property to place or not the "MenuItem" into a sub "JMenu".

This property is defined for both JMeter element kinds (Graphical or BeanInfo).
Like "menuCategories" does, "subMenuCategories" offers to place an element into multiple places (root menu and/or one/several submenus).

The definition is made like following:

Graphical kind; By Adding the "getSubMenuCategories()" method in the GUI related class and defining the returned String array:
 * "null" or [""]: lets the item in the root of the related category menu.
 * ["AAA"]: places the item into the sub menu name "AAA"
 * ["AAA", "BBB"]: places the item into the sub menu name "AAA" and into the sub menu "BBB"
 * ["", "AAA"]: places the item into the root of the related category menu and into sub menu name "AAA".

NB: If the method is missing, it does change nothing. the item remains in the root of the related category menu.
NB: The sub menu names must be translated by the resources mechanism.

BeanInfo kind; By twisting the BeanInfo "shortDescription" property to get the translated sub menu names. Several places names must be separated by ";":
 * property "shortDescription" undefined or set to "": lets the item in the root of the related category menu.
 * "AAA": places the item into the sub menu name "AAA"
 * "AAA;BBB": places the item into the sub menu name "AAA" and into the sub menu "BBB"
 * ";AAA": places the item into the root of the related category menu and into sub menu name "AAA".

Warning: general and specific resources related string must be identical or different sub menus will appears.

Developer note: I hope it will helpfull for other developpers, because I really need it for my whole sets of plugins.
I've gathered some protocol specific elements to show the efficency of the mechanism
Up to you to roll them back, gather them differently or change the name used for the submenus

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello,
Thanks for contribution.
Could you provide a screenshot of what the result will look like ?
Thank you

**Comment by vherilier** [comment]
Here's some screenshots (Only JMeter native elements are concerned by the submenu gathering):
logic controller menu
config element menu
sampler menu

**Comment by vherilier** [comment]
I missed JMS elements and I surely missed other gathering cases

**Comment by pmouawad** [comment]
Thanks a lot for your screenshots which give a better view of the feature and your work on this.

Unfortunately As discussed in :
- https://bz.apache.org/bugzilla/show_bug.cgi?id=59937
And on dev mailing list discussion:
- "Submenus for JMeter elements"

There is no real agreement on this way of presenting test element as it introduces another level of sub menus.
The grouping by protocol is interesting but Sub Menu is not for me the most ergonomic way.

**Pull request closed without merging**
