### PR TITLE
Add darklaf look and feel

### PR DESCRIPTION
**Pull request by vlsi**
See https://github.com/weisJ/darklaf/wiki/Features

Note: this PR completely removes `bulenkov/darcula` from JMeter, and it uses `darklaf/darcula` if that was selected in the users' preferences.

It works more or less, however, there are glitches (all known issues are fixed):
1) ~Checkbox and Radiobutton controls do not work when user clicks on the text label <-- this is blocker~ Fixed in https://github.com/weisJ/darklaf/issues/24#issuecomment-586488399
2) ~Disabled label in macOS / darcula theme  is black on darkgrey, so it is unreadable~
3) ~Menu is not integrated with macOS menu (no idea why)~
4) ~`darklaf` build fails under mac with `windows.h not found` (e.g. if someone tries to contribute to `darklaf`)~

Apache JMeter with bulenkov/darcula:
jmeter_darcula

Apache JMeter with weisJ/darflaf/darcula:
darklaf_darcula

Apache JMeter with weisJ/darflaf/IntelliJ (just in case):
darklaf_intellij

LaF menu:
Look and feel menu

### CODE REVIEW

**Comment by vlsi** [comment]
OK, just watch this. The tree component is 100500 times better. It is very readable, and the parent is immediately visible.

The layout of HTTP request leaves much to be desired, however, it is like that because JMeter code adjusts fonts here and there :-/

jmeter_tree

**Comment by vlsi** [comment]
Updated darklaf to 1.4.1.0 which is very usable from my point of view.

@pmouawad , @FSchumacher , what do you think if we replace the current darcula with darklaf?

**Comment by pmouawad** [comment]
@vlsi , what are the remaining issues on it ?

- Disabled label in macOS / darcula theme is black on darkgrey, so it is unreadable :( => I thin it's fixed right ?
- Menu is not integrated with macOS menu (no idea why) => Not a big problem for me, but is it for MAC OSX users ?
- darklaf build fails under mac with windows.h not found (e.g. if someone tries to contribute to darklaf) => Also not a problem for me, was it reported to the project ?

Thanks

**Comment by vlsi** [comment]
The issues have been resolved long ago

**Comment by pmouawad** [comment]
@vlsi , in this case +1 for switching

**Comment by vlsi** [comment]
I've updated the images and the description of the first message.

**Comment by pmouawad** [comment]
Hello,
I tested running on my Mac OSX, it fails with:
================================================================================
An error occurred: /private/var/folders/72/68dyl2ns1q37l4f0p5yfmg4w0000gn/T/nativeutils61999062531814/libdarklaf-macos.dylib: dlopen(/private/var/folders/72/68dyl2ns1q37l4f0p5yfmg4w0000gn/T/nativeutils61999062531814/libdarklaf-macos.dylib, 1): Symbol not found: _NSAppearanceNameDarkAqua
  Referenced from: /private/var/folders/72/68dyl2ns1q37l4f0p5yfmg4w0000gn/T/nativeutils61999062531814/libdarklaf-macos.dylib
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /private/var/folders/72/68dyl2ns1q37l4f0p5yfmg4w0000gn/T/nativeutils61999062531814/libdarklaf-macos.dylib


Regards

**Comment by vlsi** [comment]
Am I right it does not impact JMeter execution?
What is your macOS version?

**Comment by pmouawad** [comment]
Unless I misunderstand your question It does, JMeter does not start:

- 10.11.16

**Comment by vlsi** [comment]
Can you provide full error log?

**Comment by pmouawad** [comment]
I sent it to you

**Comment by vlsi** [comment]
@pmouawad , `Symbol not found: _NSAppearanceNameDarkAqua` should be fixed in 73ee2f6e713a1db57f38a11dc969c4cd54bb419c

**Comment by weisJ** [comment]
@pmouawad I would really appreciate if you could test out [this branch](https://github.com/weisJ/darklaf/pull/72) of darklaf on your machine, and tell me whether you are able to load the native library.

**Comment by pmouawad** [comment]
@weisJ  I have just tested it and it works now with your last version, Thank you !

 @vlsi , thanks for work on this, the result is nice

**Comment by pmouawad** [comment]
@weisJ , I  just tested jmeter, I am commenting on https://github.com/weisJ/darklaf/pull/72 now

**Pull request merged**
