### PR TITLE
Add AJP protocol (and test notification on dev list)

### PR DESCRIPTION
**Pull request by milamberspace**
Test Notification with a simple PR

### CODE REVIEW

**Comment by milamberspace** [comment]
Test comment notification now.

**Comment by milamberspace** [comment]
A new comment. Notification on dev list for comment seems don't works.

**Comment by stumped2** [comment]
Let's see if this triggers an email to the dev list.

**Comment by milamberspace** [comment]
Close PR. Notifications works on dev list now.

**Pull request closed without merging**
