### PR TITLE
Added a Graphite sender to send metrics in statsd protocol

### PR DESCRIPTION
**Pull request by nitinpadalia**
Will help to integrate Jmeter with statsd

### CODE REVIEW

**Comment by FSchumacher** [comment]
Thanks for your contribution.

As you can see, the checks for this PR are failing. You can find the reason by following the link (small red cross next to the commit id) to the travis ci site (hint: you are using tabs instead of spaces).

Apart from those cosmetic things, there are a few other issues, that I noticed.

There is a useless import of `GenericKeyedObjectPool` (maybe more, I haven't checked).
I have found one `SocketOutputStream` (named `out` and initialized to `null`), that is not used.
`Collection#size() > 0` is used to check, whether that collection is empty. You could use the `isEmpty()` method for that, since it can be more efficient and is more concise.
Exceptions get logged as `String`. It would (most of the time) be nice to add them as such to the logging instruction.

Regards,
 Felix

**Comment by sebbASF** [comment]
Thanks.
Also, I'm not sure why there is a separate private send method. It is only used once, and handles only some exceptions. The caller then catches Exception which seems wrong; it should only catch known thrown exceptions. Also the caller should probably use finally to drop the metrics.

**Comment by nitinpadalia** [comment]
Thanks! for reviews; I'll be incorporating your comments.

**Comment by pmouawad** [comment]
@nitinpadalia  , any update on this PR ?
Thanks

**Comment by nitinpadalia** [comment]
Apologies for delay I'll close this week only.

**Comment by pmouawad** [comment]
No problem. Will you submit a new PR taking into account the comments ? 
Thanks

**Comment by nitinpadalia** [comment]
Sure if that is needed... else could be using the same

**Pull request closed without merging**
