### PR TITLE
Move to JUnit5 for JUnit test execution

### PR DESCRIPTION
**Pull request by vlsi**
Note: JUnit3 and JUnit4 tests can still be executed, however it makes sense to use JUnit5 for new tests

## Motivation and Context

JUnit5 has multiple API enhancements, so it makes sense to migrate to JUnit5.

Note: Gradle-JUnit5 chokes when it faces JUnit3 test suites with duplicate test names.
I'm not sure if it is a bug in JUnit or in Gradle, and I just add `Describable` implementation for the tests so they return different `uniqueId` values, so it works.
I think it is fine, and we hopefully could migrate those tests to JUnit5 or Spock alternatives.

### CODE REVIEW

**Comment by vlsi** [comment]
@pmouawad ,  @FSchumacher , any comments?
I'm inclined to commit this.

**Comment by pmouawad** [comment]
Hi @vlsi ,
It looks like a good idea.
Do you intend a full migration ?

Are tests taken into account for coverage ?

Also, by the way, I'm not sure whether you already commented about it (I think you did but can't find the item), but what is the reason for the drop in coverage of:
https://builds.apache.org/analysis/overview?id=org.apache.jmeter%3AJMeter
Where do we find the up to date alternative ?

Thanks

**Comment by vlsi** [comment]
> Do you intend a full migration ?

Full migration is possible, however it can be incremental.
JUnit 5 can execute both JUnit3/4/5 test styles.

>Are tests taken into account for coverage ?

As you see https://github.com/apache/jmeter/pull/496#issuecomment-533908637, the coverage diff is minimal, so the reported coverage is the same as before.

> https://builds.apache.org/analysis/overview?id=org.apache.jmeter%3AJMeter
> Where do we find the up to date alternative ?

Current Sonar is https://sonarcloud.io/dashboard?id=JMeter

**Comment by vlsi** [comment]
I've filed JUnit5 issue to process `TestSuite`s properly: https://github.com/junit-team/junit5/issues/2021

Current JUnit5 produces silent failures (see https://travis-ci.org/apache/jmeter/jobs/588172857#L857-L858 ) which is not good, and it would take certain effort to migrate `org.apache.jmeter.functions.PackageTest`.

**Comment by vlsi** [comment]
It turns out JUnit5's executor of JUnit3 tests is fragile for cases when multiple tests have the same name, and the fix does not seem to be trivial (see https://github.com/junit-team/junit5/issues/2021 ).

So let's wait Marc's answer for a bit, however it looks like it's time to migrate `TestSuite`-based tests to JUnit5, which might be nice anyway, because current `suite()`-based approach make it complicated to run individual tests from the IDE.

**Comment by vlsi** [comment]
I've rewritten XPath and CSV tests from `functions.PackageTest` to JUnit 5, and it turns out there's a bug (or feature) in `XPath`.

The question there is how `XPath` function resets its internal state.
Currently repeated execution do not reset state (which is cached in a threadlocal), thus the test fails if I execute it multiple times.

**Pull request merged**
