### PR TITLE
feat: use ServiceLoader to find implementations instead of searching classes in jars

### LINKED ISSUE #5883: Use ServiceLoader to find implementations instead of ClassFinder
### Use case

There should be a possibility to launch JMeter without hand-crafting a special file layout.
For instance, when running unit tests, it is hard to prepare all the jars in the appropriate folders.

### Possible solution

Use  `java.util.ServiceLoader` to lookup implementations so the users could provide implementations via Java classpath.

### Possible workarounds

_No response_

### JMeter Version

5.5

### Java Version

_No response_

### OS Version

_No response_

### PR DESCRIPTION
**Pull request by vlsi**
## Description

ServiceLoader is Java standard approach for locating implementaitons, and it allows pluggability without relying on a filesystem layout.

The change is backward-compatible, so JMeter searches implementations via `ServiceLoader`, and then it scans the jars like it was doing previously. However, all the JMeter-provided implementations would be provided as services.

Fixes https://github.com/apache/jmeter/issues/5883
See discussion https://lists.apache.org/thread/4t7wcjh45q61v300j1954c8l8931swrr

TODO:
* [x] add `JMeterUtils#loadServices` and tests
* [x] migrate `JMeterUtils#findClassesThatExtend` usages to `ServiceLoader`
* [x] migrate `ClassFinder#findClassesThatExtend` usages to `ServiceLoader`
* [x] deprecate `ClassFinder` methods
* [x] Add Jar manifest entry `JMeter-Skip-Class-Scanning: true` so `ClassFinder` ignores JMeter jars
* [x] Add javadocs when appropriate
* [x] Add changelog entry
* [x] fix `The Kotlin Gradle plugin was loaded multiple times in different subprojects` warning

Out of scope of the PR:
* [ ] https://github.com/apache/jmeter/issues/5895
  migrate `MenuFactory` from `ClassFinder#findClassesThatExtend`
  `MenuFactory` is tricky as `ServiceLoader` instantiates services by default, so we can't use it for heavy-weight objects. `MenuFactory` makes extra efforts to avoid creating all the GUI components, so we should suggest an alternative.
* [x] migrate `ActionRouter`. The code there is involved, and it is not clear why it searches for classes several times (see https://github.com/apache/jmeter/commit/574ceb61aed9de91147aa72b71a6097e6258eef3), implemented in b15439e340b6c566fddc41874257d7a200455496

## Motivation and Context

The current `JMeterUtils#findClassesThatExtend` and `ClassFinder.findClassesThatExtend` impose issues:
1) They expect classes to be packaged in jars. It is inconvenient for testing purposes where the dependencies might come form `classes` folders
2) Class scanning takes time. The current workaround is to use `String contains, String notContains` parameters, however, it does not resolve the issue, and it makes an awkward API overall
3) It will make it easier to create tests. For instance, I want to use `__counter` function for https://github.com/apache/jmeter/pull/5788 in `:src:core` test module, however, `ClassFinder` does not work there as it wants jar files. After migration to `ServiceLoader`, I could add `testRuntimeOnly(projects.src.functions)` dependency, and then `CompoundVariable` would be able to locate functions with a `ServiceLoader`.

### CODE REVIEW

**Comment by vlsi** [comment]
@FSchumacher , @emilianbold, do you remember the reasons for https://github.com/apache/jmeter/commit/574ceb61aed9de91147aa72b71a6097e6258eef3 by chance?

**Comment by vlsi** [comment]
It looks like the extra overhead for annotation processing is negligible, so I think we can live with it.

I've tried `./gradlew testClasses --rerun-tasks --no-build-cache`, and it looks like the difference does not exceed 7 seconds.

#### with annotation processing

```
BUILD SUCCESSFUL in 1m 36s
197 actionable tasks: 197 executed
```

https://ge.apache.org/s/td4x7pa3gnddm

#### before this PR

```
BUILD SUCCESSFUL in 1m 29s
186 actionable tasks: 186 executed
```

https://ge.apache.org/s/wevuaxhuqoonw

**Comment by vlsi** [comment]
I think the PR is good to go (if the tests pass). I will merge it soon provided there are no objections.

**Comment by milamberspace** [comment]
@vlsi you want release 5.5.1 with xalan security fix before merge this PR? Or we prepare the next release 5.6 or 6.0?

**Comment by Mingun** [comment]
@vlsi, you're crazy man. Why all the changes in one commit? How to understand which interfaces supports new annotation?

**Comment by vlsi** [comment]
@Mingun , please check the tutorial update which comes within the PR: https://github.com/apache/jmeter/pull/5885/files#diff-576fa49214b48be798a06fe0b81dbd6b0276fa58b0c46fd081c278bab7f00a63R183-R184

```
      The interfaces that are supported for service loading are marked with
      <code>org.apache.jorphan.reflect.JMeterService</code>
      annotation.
```

**Comment by vlsi** [comment]
Try `find usages` for `JMeterService` in the IDE.

**Pull request merged**
