### PR TITLE
Static Analysis Fixes

### PR DESCRIPTION
**Pull request by ham1**
Hopefully each commit is small enough to review and apply (and at least some of this is useful) please let me know if not.

Improvements based largely upon static analysis to improve readability and utilise Java 8 features:
* Simplify return statements
* Simplify conditional expressions
* Utilising lambdas, streams API, computeIfAbsent and method references
* Removed duplicate throws
* Removed redundant throws
* Used ThreadLocal.withIntial
* Used forEach, addAll and arraycopy to improve readability
* Replaced StringBuilder with + to improve readability
* Formatting, spelling and minor refactors
* Removed some deprecated calls

### CODE REVIEW

**Comment by pmouawad** [comment]
@ham1 , Thanks a lot for your contribution.
Looks globally good for me.
I have just one remark, I wouldn't "optimize" the org.apache.jmeter.control package classes.
This part of JMeter is one of the most complex and less readable.
We need by the way to increase our Test coverage on these.

**Comment by pmouawad** [comment]
Hello, 
Another question I have.
I see you replace StringBuilder by '+' concat.
Is there a reason for this ?
Reading:
- http://www.pellegrino.link/2015/08/22/string-concatenation-with-java-8.html

I don't understand that their performance is better.
Do you have another reference ?
Thanks

**Comment by ham1** [comment]
Thanks for looking at the PR and commenting.

I will take another look at the changes to `org.apache.jmeter.control` and either revert or justify them.
I'd gladly add more tests if we move to Spock ;)

The reason for replacing `StringBuilder` with `+` is for **readability**.

That article shows, that for the simple code i.e. not building a string inside loops etc. they are the same i.e. the JVM generates a `StringBuilder` for the simple `+` code.
I believe they have the same performance but for me reading:

`"nodeList[" + i + "] " + nodeList.item(i)`
is much easier than:
`new StringBuilder("nodeList[").append(i).append("] ").append(nodeList.item(i)).toString()`

and

`"Row: " + row`
much easier than:
`new StringBuilder("Row: ").append(row).toString()`

My change in `InfluxdbBackendListenerClient` might be a tiny bit slower due to the initial capacity that the JVM might use the default of 16 causing some resizing of buffers.

Hope that makes sense.

**Comment by ham1** [comment]
After reviewing my changes to `org.apache.jmeter.control` they were all suggested by my IDE (IntelliJ) so I am confident they are correct - however I understand if you don't want to apply some of them due to lack of tests etc.

Should I remove them from this PR or is whoever will apply this ok to filter out any risky changes?

**Pull request closed without merging**
