### PR TITLE
Updated checkstyle and added MissingDeprecated check, also formatted

### PR DESCRIPTION
**Pull request by ham1**
## Description
Added extra checkstyle rule and updated to 8.23 (8.24 is the current latest but it causes a lot more errors, especially usage of `<` and `>` in JavaDoc).

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by vlsi** [comment]
@ham1 , have you seen https://github.com/diffplug/spotless?
I guess we might want to move some of checkstyle rules to spotless since the latter enables `./gradlew spotlessApply` to automatically apply the fixes like "import order", "spacing", "wrong file header", etc, etc.

**Comment by ham1** [comment]
I had not seen that before. Auto-fixing of spacing, import order and header etc. sounds good!

**Comment by ham1** [comment]
Opps I missed the checksums.

**Comment by vlsi** [comment]
@ham1 , I see you contribute a lot of cleanup, and that is nice.
Re Spotless, it might look as follows:  https://travis-ci.org/vlsi/vlsi-release-plugins/jobs/584025923#L410
That is way better than Checkstyle.

**Comment by ham1** [comment]
I agree it's nice because fixes can be auto applied, but they can't be applied in CI, and it doesn't seem to have as many rules, so I do not yet see how it is much better than Checkstyle, maybe I've missed something? Maybe a topic for the mailing list?

**Comment by vlsi** [comment]
1) Both tools can't autofix code in CI
2) Spotless can autofix code in dev machine
3) Spotless prints much more meaningful messages.

=> Spotless is better

**Comment by vlsi** [comment]
Adding `final` all over the place might easily break backward compatibility.
Is there a good reason for retrofitting finals all over the place?

**Comment by ham1** [comment]
Good point. I believe the rule is there for those classes who cannot be extended anyway because they have private default constructors and therefore either can't be or probably shouldn't be extended.

From the docs:
    Checks that a class which has only private constructors is declared as final. Doesn't check for classes nested in interfaces or annotations, as they are always final there.

**Pull request closed without merging**
