### PR TITLE
BZ61466: Comment addition to SampleResults

### PR DESCRIPTION
**Pull request by vherilier**
The goal of this PR is to allow SampleResult to embed the related Comment/Description value to be reused by any Reporter or Listener elements to publish more accurate test result content.
By example, PerfPublisher files (likely used with Jenkins application) focus highly about testcases description for test results reporting and in JMeter, the more close of such element is the Transaction Controller.

That's why I propose with this PR, and for a first step, to store at least Transaction Controllers description into SampleResult new property "Comment"; for other samplers result, only an empty string (it could be extended if you estimate is has to be done to give description of test steps too).

I hope it will act in JMeters' interest to be more accurately integrated with Continuous Integration applications.

BR,
--Vincent Hérilier

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello @vherilier ,
Thanks for PR.

Could you amend it to:
- Add a property that would apply to all TC
- add a TristateCheckBox in GUI  'Use comment in SampleResult'

I think this will cover all cases:

- Send comments for ALL TC
- Don't send comments
- Send for all except some
- Send for none except some

And test this value to add it to sampler.
Of course JUnit are welcome.

I'll be happy to merge it once done.
Thank you.

**Comment by vherilier** [comment]
I'll do it ASAP.
Thank you for the suggestion.

**Comment by vherilier** [comment]
Hello @pmouawad ,

Hope it will cover your suggestion :)

**Comment by pmouawad** [comment]
Thanks @vherilier  for your update, it looks good to me.

May I ask one last thing, there is no documentation nor illustration of how this feature can be used.
So if we want this feature to be popular there should be some sexy use case showing an example integration with some screenshot.
Thanks

**Comment by vherilier** [comment]
Hi @pmouawad ,

Starting the feature documentation part, an issue came to me about about how and where defining the global property.
"Sampler Result Save configuration" properties could proposed this new one directly and the .jtl could integrate it because .jtl files cold be used to generate test results reports too.

What do you think about ?

BR,
--Vincent

**Comment by pmouawad** [comment]
Hello @vherilier ,
There is indeed a problem (good catch) as this new field should be persisted to XML/CSV.
But my issue here is that it only concerns Transaction Controller and would be in SampleResult.

Should we use it everywhere instead of limiting it to Transaction Controller ?

At Team,  what's your thought ?

@vherilier , could you show some report were feature is used so that we can grasp the benefit of it ?

Thanks

**Comment by vherilier** [comment]
I attached an archive that contains 2 files:
* a EXP.jtl one
* a EXP.xml one containing PerfPublisher test results content used in my case by Jenkins to manage test results reports and comparisons.

[reporter.zip](https://github.com/apache/jmeter/files/1382987/reporter.zip)

Only testcases results are reported (not their test step ones) for PerfPublisher and they matches Transaction Controllers elements in the related .jmx file

IMHO, in .jtl files, "comments" should be added too because it may improve test reporting accuracy even from a .jtl file

**Comment by vlsi** [comment]
Note: this PR was automatically closed when JMeter development moved from SVN to Git (main branch was renamed from `trunk` to `master`, thus GitHub closed the PR).
If you want to revive the PR, please update your fork as per https://github.com/vlsi/jmeter-git-cleanup/tree/v2.2.0/clean_fork , reopen the PR (unfortunately, it has to be a new PR).

If you have questions, please feel free to ask on JMeter dev list.

Sorry for the inconvenience

**Pull request closed without merging**
