### PR TITLE
Support SVG icons for the toolbar

### PR DESCRIPTION
**Pull request by vlsi**
## Description

This change enables to use of SVG icons for the toolbar.

## Motivation and Context

png images do not always look good at HiDPI screens since it requires to generate multiple copies of the image.

In practice, JMeter's toolbar does not provide 2x scaled images, so the pixels are clearly visible.

## Screenshots (if appropriate):

Note the icon in the middle

<table>
<tr><th>Theme</th><th>Before</th><th>After</th></tr>
<tr><td>IntelliJ</td>
<td>
Снимок экрана 2020-03-19 в 23 47 55
</td><td>
Снимок экрана 2020-03-19 в 23 49 38
</td></td>
<tr><td>Solarized dark</td>
<td>
Снимок экрана 2020-03-19 в 23 48 18
</td><td>
Снимок экрана 2020-03-19 в 23 49 17
</td></td>
</table>

### CODE REVIEW

**Comment by weisJ** [comment]
If the svg icon doesn’t contain any colour, which needs to be resolved at runtime, there is still `DarkSVGIcon`. Also I think at some point the icons should be overhauled as they are too detailed to work in the scale they are used.

**Comment by vlsi** [comment]
> Also I think at some point the icons should be overhauled as they are too detailed to work in the scale they are used.

That is true. It should be something like "use this URL for icons 31px+, this URL for 17..31px, and this for 0..16px".

That, however, is a bit different story (==> different PR).

**Comment by weisJ** [comment]
> That is true. It should be something like "use this URL for icons 31px+, this URL for 17..31px, and this for 0..16px".
> 

Or simply an icon that works in all sizes.

> That, however, is a bit different story (==> different PR).

That is true :D

**Comment by vlsi** [comment]
I just learned IntelliJ platform requires plugin logos to be in SVG format: https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html#plugin-logo-file-format

**Pull request merged**
